# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0biczh3siq3dj619493ps0sg24gyyjf52kfpsfkqv8bjn6mx0jiz";
    aarch64-linux = "0m9772lrihij5aa3y11pcrf3n5y3yszdw4b6rak0m05akaqfprg7";
    x86_64-darwin = "16z16g0ic3g8l5qjh2746a51wg3vakfbf6d6gpp3f56pn9916mny";
    aarch64-darwin = "08fvrd41nq6i6py30la4f33sqv3my1pkg8mqsy984a38w0c4hhai";
  };

  urlMap = {
    x86_64-linux = "https://github.com/darksworm/traefiktop/releases/download/v1.0.1/traefiktop-1.0.1-linux-amd64.tar.gz";
    aarch64-linux = "https://github.com/darksworm/traefiktop/releases/download/v1.0.1/traefiktop-1.0.1-linux-arm64.tar.gz";
    x86_64-darwin = "https://github.com/darksworm/traefiktop/releases/download/v1.0.1/traefiktop-1.0.1-darwin-amd64.tar.gz";
    aarch64-darwin = "https://github.com/darksworm/traefiktop/releases/download/v1.0.1/traefiktop-1.0.1-darwin-arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "traefiktop";
  version = "1.0.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./traefiktop $out/bin/traefiktop
  '';

  system = system;

  meta = {

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
