# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0a98hp5b5j3irwk574ws5f8pjdwjjhwxzi9alhw8043316vjk8wj";
    aarch64-linux = "0cphd720j0cy5b5yjxg108296jak5id25wx4if2b1qjg97cay29a";
    x86_64-darwin = "11wjihg5ay8w6pvwy1y9pd89sl6aa5ypxzn3q9pbxnbn75xampas";
    aarch64-darwin = "1mhx8889r95az5dfvcvqfx7d7dak46dn79cvf8xiqr8l4x37rvgr";
  };

  urlMap = {
    x86_64-linux = "https://github.com/darksworm/traefiktop/releases/download/v1.0.0/traefiktop-1.0.0-linux-amd64.tar.gz";
    aarch64-linux = "https://github.com/darksworm/traefiktop/releases/download/v1.0.0/traefiktop-1.0.0-linux-arm64.tar.gz";
    x86_64-darwin = "https://github.com/darksworm/traefiktop/releases/download/v1.0.0/traefiktop-1.0.0-darwin-amd64.tar.gz";
    aarch64-darwin = "https://github.com/darksworm/traefiktop/releases/download/v1.0.0/traefiktop-1.0.0-darwin-arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "traefiktop";
  version = "1.0.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./traefiktop $out/bin/traefiktop
  '';

  system = system;

  meta = {

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
