# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0r2vvw5vs4ydwyf1y1ir77k105grhhvjvpqhxdxid7w0hjpp9mzp";
    aarch64-linux = "1kq7ikw3ax2bj26fica93hcg3bc9py3x1q7gi8v36jwck9a8k90i";
    x86_64-darwin = "0k849sr5wfg367y3xa1fsl6rk9026m8ynindb0z8adk1fa9l9j8n";
    aarch64-darwin = "14jqbmll96iy97bafl72yrdy44i32l1jmc766zgj2j20gmh3625m";
  };

  urlMap = {
    x86_64-linux = "https://github.com/darksworm/traefiktop/releases/download/v1.1.1/traefiktop-1.1.1-linux-amd64.tar.gz";
    aarch64-linux = "https://github.com/darksworm/traefiktop/releases/download/v1.1.1/traefiktop-1.1.1-linux-arm64.tar.gz";
    x86_64-darwin = "https://github.com/darksworm/traefiktop/releases/download/v1.1.1/traefiktop-1.1.1-darwin-amd64.tar.gz";
    aarch64-darwin = "https://github.com/darksworm/traefiktop/releases/download/v1.1.1/traefiktop-1.1.1-darwin-arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "traefiktop";
  version = "1.1.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./traefiktop $out/bin/traefiktop
  '';

  system = system;

  meta = {

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
