# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "1w6nd5hx02wdg6mmsrlp5nibjgm55knw39nlzw4c10gb1npx7zfl";
    aarch64-linux = "1m22yb431x81d02wcr24xbyhxp1ichjwfbs7410camll7758m461";
    x86_64-darwin = "18bscjggb6hg6878a3bsj769jr24rhszkmam571qlq93y4iky94m";
    aarch64-darwin = "0dppdfxvhphm3k7hyncp2nzkcdavfhdlzn9hjsh89dkr9mvk4264";
  };

  urlMap = {
    x86_64-linux = "https://github.com/darksworm/argonaut/releases/download/v1.13.0/argonaut-1.13.0-linux-amd64.tar.gz";
    aarch64-linux = "https://github.com/darksworm/argonaut/releases/download/v1.13.0/argonaut-1.13.0-linux-arm64.tar.gz";
    x86_64-darwin = "https://github.com/darksworm/argonaut/releases/download/v1.13.0/argonaut-1.13.0-darwin-amd64.tar.gz";
    aarch64-darwin = "https://github.com/darksworm/argonaut/releases/download/v1.13.0/argonaut-1.13.0-darwin-arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "argonaut";
  version = "1.13.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./argonaut $out/bin/argonaut
  '';

  system = system;

  meta = {

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
