# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "02amg1q7c441i6fg1xhqbc64lnpwwn63lpip58bpia2hlkz0kyw6";
    aarch64-linux = "0isg3ap3fgn27lsv2xbgmh2qwa8szxqia1vvq9av48kmv7fmcwj3";
    x86_64-darwin = "0l42kscxhm9rczxnrfd5046sdc1sz76vsm2y9scms65ivcn4nws7";
    aarch64-darwin = "1jbxjx61kayy2n5dxpjb8vy4csbw5ygqp2n158ivlwmza7av4w23";
  };

  urlMap = {
    x86_64-linux = "https://github.com/darksworm/argonaut/releases/download/v1.16.1/argonaut-1.16.1-linux-amd64.tar.gz";
    aarch64-linux = "https://github.com/darksworm/argonaut/releases/download/v1.16.1/argonaut-1.16.1-linux-arm64.tar.gz";
    x86_64-darwin = "https://github.com/darksworm/argonaut/releases/download/v1.16.1/argonaut-1.16.1-darwin-amd64.tar.gz";
    aarch64-darwin = "https://github.com/darksworm/argonaut/releases/download/v1.16.1/argonaut-1.16.1-darwin-arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "argonaut";
  version = "1.16.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./argonaut $out/bin/argonaut
  '';

  system = system;

  meta = {

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
