# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "197ji7b3f4qd1l2gsrgl75kzpqyfmnqy5n7ms4dhy63c86qjz92y";
    aarch64-linux = "0xrvsz6162ac7rjdgdisk2nw1dsrfhv8dsf7ksnq76d6wkrnz3q1";
    x86_64-darwin = "0njf3rlcqyrwfwl7h9v6qlhkm1bpyxwizl8kjmlbbj2ad8bzfcyq";
    aarch64-darwin = "03906mhrz87rpqijcf8nlavzx0smfv38rrchiblpk02ahf89k7kv";
  };

  urlMap = {
    x86_64-linux = "https://github.com/darksworm/argonaut/releases/download/v1.10.2/argonaut-1.10.2-linux-amd64.tar.gz";
    aarch64-linux = "https://github.com/darksworm/argonaut/releases/download/v1.10.2/argonaut-1.10.2-linux-arm64.tar.gz";
    x86_64-darwin = "https://github.com/darksworm/argonaut/releases/download/v1.10.2/argonaut-1.10.2-darwin-amd64.tar.gz";
    aarch64-darwin = "https://github.com/darksworm/argonaut/releases/download/v1.10.2/argonaut-1.10.2-darwin-arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "argonaut";
  version = "1.10.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./argonaut $out/bin/argonaut
  '';

  system = system;

  meta = {

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
